# Generated by Django 4.2.8 on 2025-01-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fields',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='reservoirs',
            options={'verbose_name': 'Reservoir', 'verbose_name_plural': 'Reservoirs'},
        ),
        migrations.AlterModelOptions(
            name='tubeconnection',
            options={'verbose_name': 'TubeConnection', 'verbose_name_plural': 'TubeConnections'},
        ),
        migrations.AlterModelOptions(
            name='tubular',
            options={'verbose_name': 'Tubular', 'verbose_name_plural': 'Tubulars'},
        ),
        migrations.AlterModelOptions(
            name='tubulartemp',
            options={'verbose_name': 'TubularTemp', 'verbose_name_plural': 'TubularTemps'},
        ),
        migrations.AlterModelOptions(
            name='wells',
            options={'verbose_name': 'Well', 'verbose_name_plural': 'Wells'},
        ),
        migrations.RemoveField(
            model_name='wells',
            name='add_by',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='wells',
            name='is_approved',
        ),
    ]
