# Generated by Django 4.2.8 on 2025-01-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0002_alter_country_options_alter_fields_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubeconnection',
            name='add_by',
        ),
        migrations.RemoveField(
            model_name='tubular',
            name='add_by',
        ),
        migrations.RemoveField(
            model_name='tubulartemp',
            name='add_by',
        ),
    ]
