version: "3.9"

services:  
  web:
    container_name: web
    platform: linux/amd64
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home
    ports:
      - 8000:8000
   
      
  
  
